version: '3'
services:
  frontend:
    build:
      context: /home/ubuntu/tech3tier-app/Techdome-frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: /home/ubuntu/tech3tier-app/Techdome-backend
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
